export const defaultPage = {
  primaryColor: { r: 65, g: 5, b: 160, a: 0.3 },
  secondaryColor: { r: 151, g: 71, b: 255, a: 0.3 },
  fontColor: "#f1f1f1",
  pfpUrl: "/defaultpfp.jpg",
  bgUrl: "/bg.svg",
  bgSize: "cover",
  bgOpacity: 0.3,
  cardBlur: "backdrop-blur",
  cardHueRotate: "",
  cardSepia: "",
  pageSocialMedias: [{ username: "https://zoz.bio/", key: "website" }],
  pageBadges: ["welcome", "new", "zoz", "member"],
  pageStatus: { key: "sleepo", message: "sleeping~" },
};
